### ISSUE TITLE
Assets path must be set as array

### ISSUE THREAD

**Issue by gbdrummer** [coreybutler/productionline-web#2]
```js
builder.assets = path.resolve('./assets')
```
throws this error:
<img width="568" alt="screen shot 2018-04-30 at 12 58 41 pm" src="https://user-images.githubusercontent.com/3631962/39447560-ffb9eb26-4c76-11e8-8593-0899d36c3d19.png">

Instead you currently have to use:
```js
builder.assets = [path.resolve('./assets')]
```

**Comment by coreybutler** [comment]
This issue is in productionline, not productionline-web.
